name: Deploy JHipster Application to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # Specify the JDK distribution

    - name: Build with Maven
      run: ./mvnw -Pprod clean package -DskipTests

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-jar
        path: target/monorsm-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: app-jar

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EC2
      run: |
        scp -i ~/.ssh/aws-key.pem monorsm-0.0.1-SNAPSHOT.jar ec2-user@<EC2-PUBLIC-IP>:/home/ec2-user/
        ssh -i ~/.ssh/aws-key.pem ec2-user@<EC2-PUBLIC-IP> << EOF
        sudo yum update -y
        sudo yum install java-17-openjdk -y
        nohup java -jar /home/ec2-user/monorsm-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
        EOF
